# Generated by Django 5.2.13 on 2026-04-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('role', models.CharField(default='Life Insurance Agent', max_length=50)),
                ('joined_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parameter_json', models.JSONField(default=dict, help_text='e.g. {"speed_ratio_threshold": 0.2} - read by rules engine')),
                ('severity_level', models.CharField(choices=[('Low', 'Low'), ('Med', 'Medium'), ('High', 'High')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-severity_level', 'rule_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('expected_duration_seconds', models.IntegerField(default=420, help_text='Target reading time (seconds). Default 7min = 420s.')),
                ('company_avg_seconds', models.IntegerField(default=380, help_text='Rolling company-wide average completion time.')),
                ('card_count', models.IntegerField(default=5)),
                ('quiz_question_count', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (False Alarm)'), ('voided', 'Voided & Retake Required'), ('escalated', 'Escalated to HR')], default='pending', max_length=20)),
                ('evidence', models.JSONField(default=dict, help_text='Captured values the rules engine compared against thresholds')),
                ('leaderboard_points_revoked', models.BooleanField(default=False)),
                ('streak_shield_locked', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='compliance.agent')),
                ('rule_violated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags', to='compliance.compliancerule')),
            ],
            options={
                'ordering': ['-flag_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(default='Compliance Officer', max_length=100)),
                ('action_taken', models.CharField(choices=[('approved', 'Approve (False Alarm)'), ('voided', 'Void Session & Require Retake'), ('escalated', 'Escalate to HR')], max_length=20)),
                ('manager_justification_notes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='compliance.flaggedsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_seconds', models.IntegerField()),
                ('quiz_score_percent', models.IntegerField(default=0)),
                ('quiz_time_seconds', models.IntegerField(default=0)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('abandoned', 'Abandoned')], default='completed', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='compliance.agent')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='compliance.trainingmodule')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_seconds', models.IntegerField(help_text='Seconds from session start')),
                ('event_type', models.CharField(choices=[('start', 'Session Start'), ('tab_switch_away', 'Switched To External App'), ('tab_switch_back', 'Returned To Training'), ('card_view', 'Flashcard Viewed'), ('card_swipe', 'Flashcard Swiped'), ('quiz_start', 'Quiz Started'), ('quiz_answer', 'Quiz Answered'), ('quiz_submit', 'Quiz Submitted'), ('complete', 'Session Complete')], max_length=32)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='compliance.trainingsession')),
            ],
            options={
                'ordering': ['offset_seconds', 'id'],
            },
        ),
        migrations.AddField(
            model_name='flaggedsession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='compliance.trainingsession'),
        ),
        migrations.AddIndex(
            model_name='flaggedsession',
            index=models.Index(fields=['resolution_status'], name='compliance__resolut_3eb8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedsession',
            index=models.Index(fields=['-flag_timestamp'], name='compliance__flag_ti_360871_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flaggedsession',
            unique_together={('session', 'rule_violated')},
        ),
    ]
