# Generated by Django 5.2.13 on 2026-04-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complianceauditlog',
            old_name='manager_name',
            new_name='manager_id',
        ),
    ]
